version: 2
jobs:
  build:
    working_directory: ~/todoFlaskApi
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          command: |
            python3 -m venv flaskVenv
            . flaskVenv/bin/activate
            ls >> prueba.txt
            cat prueba.txt           
            pip3 install -r ~/todoFlaskApi/requirements.txt
      - run:
          command: |
            . flaskVenv/bin/activate
            pytest            