version: 2
jobs:
  build:
    working_directory: ~/todoFlaskApi
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          command: |
            python3 -m venv flaskVenv
            . flaskVenv/bin/activate
            cd ~/todoFlaskApi                
            pip3 install -r requirements.txt
      - run:
          command: |
            . flaskVenv/bin/activate
            pytest            