"""empty message

Revision ID: 239a2d8ac940
Revises: 95acb0d546af
Create Date: 2019-08-18 10:07:32.224346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239a2d8ac940'
down_revision = '95acb0d546af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'start_date')
    # ### end Alembic commands ###
